version: '3.8'

services:
  api:
    build: .
    ports:
      - 8000:8000
    depends_on:
      - wanteddb
  wanteddb:
    image: postgres:14.9
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fok
      POSTGRES_PASSWORD: fok
      POSTGRES_DB: mostwanted
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - db:/var/lib/postgresql/data/pgdata
volumes:
  db:
    driver: local